### ISSUE TITLE
Loading icon doesn't spin in Firefox

### ISSUE THREAD

**Issue by bytorbrynden** [Team-Delta-KA/KA-Contest-Judging-System#13]
Title says it all.

**Comment by Noble-Mushtak** [comment]
I have both Firefox and Chromium, so I'll work on this right now!

**Comment by bytorbrynden** [comment]
Alright; great. Assigning this issue to you.

**Comment by MrMagma** [comment]
I don't think I should submit it as a bug here since it's something wrong with FF/KA's embed code, but neither the code editor or the canvas will render on FF. I'm going to submit a bug report to KA about this. I thought this would be good to know for the project
(Update:Should check my email before posting)

**Comment by Noble-Mushtak** [comment]
Fixed it! We just needed to add a Mozilla animation along with the keyframes and the Webkit animation.

**Comment by bytorbrynden** [comment]
@JavascriptFTW; There's another issue that I opened for the entry preview's not loading...

https://github.com/Team-Delta-KA/KA-Contest-Judging-System/issues/14

**Comment by codeHusky** [comment]
Since the fix is merged, I'm going to close this.
