### ISSUE TITLE
Firebase Auth Popup is blocked by most browsers' popup blocker

### ISSUE THREAD

**Issue by bytorbrynden** [Team-Delta-KA/KA-Contest-Judging-System#23]
The way I have it implemented currently, the Firebase Auth Popup shows up any time you visit an entry. This gets blocked by most browsers' popup blocker.

**Comment by Noble-Mushtak** [comment]
Just don't authenticate until the judge tries to submit an entry and then authenticate the judge with the popup once they click. If the authentication fails, instead of redirecting to `permissionDenied.html` (that would be kind of unnatural after they've already visited the page), just use `alert()` to tell them that they're not a judge.

**Comment by Noble-Mushtak** [comment]
This issue has been solved by the above pull request and should be closed.
